# frozen_string_literal: true

module SolidRun
  class CLI
    VERSION = "0.1.0"

    attr_reader :options

    def self.run(argv = ARGV)
      new(argv).run
    end

    def initialize(argv = ARGV)
      @argv = argv
      @options = {
        port: 4567,
        remote: "origin",
        events: Webhook::DEFAULT_EVENTS,
        secret: SecureRandom.hex(20),
        insecure: false,
        act: true,
        act_args: [],
        report_status: true
      }
      parse_options!
    end

    def run
      print_banner

      git = Git.new(remote_name: @options[:remote])
      puts "📁 Detected repository: #{EventPrinter::BOLD}#{git.full_name}#{EventPrinter::RESET} (remote: #{git.remote_url})"

      secret = @options[:insecure] ? nil : @options[:secret]

      act_runner = ActRunner.new(
        repo_full_name: git.full_name,
        extra_args: @options[:act_args],
        report_status: @options[:report_status]
      )

      on_event = proc do |event_type, payload, delivery_id|
        EventPrinter.print(event_type, payload, delivery_id: delivery_id)
        act_runner.execute(event_type, payload) if @options[:act]
      end

      server = Server.new(port: @options[:port], secret: secret, on_event: on_event)
      server.start

      tunnel = Tunnel.new(port: @options[:port])
      tunnel_url = tunnel.start

      webhook = Webhook.new(repo_full_name: git.full_name, tunnel_url: tunnel_url, secret: secret)
      webhook.register(events: @options[:events])

      # Graceful shutdown handler
      shutdown_proc = proc do
        puts "\n\n👋 Shutting down Local CI Runner..."
        webhook.delete
        tunnel.stop
        server.stop
        puts "🎉 Everything cleaned up successfully. Have a great day!"
        exit 0
      end

      Signal.trap("INT") { shutdown_proc.call }
      Signal.trap("TERM") { shutdown_proc.call }

      puts "\n" + ("=" * 60)
      puts "👂 #{EventPrinter::GREEN}Local CI is LIVE and ready to run workflows!#{EventPrinter::RESET}"
      puts "   Tunnel URL : #{tunnel_url}"
      puts "   Webhook    : #{tunnel_url}/webhook"
      puts "   Security   : #{secret ? "#{EventPrinter::GREEN}HMAC-SHA256 active#{EventPrinter::RESET}" : "#{EventPrinter::RED}Insecure (No signature check)#{EventPrinter::RESET}"}"
      puts "   Runner     : #{@options[:act] ? "#{EventPrinter::GREEN}act (Docker enabled)#{EventPrinter::RESET}" : "#{EventPrinter::YELLOW}Listen-only (act disabled)#{EventPrinter::RESET}"}"
      puts "   Listening  : #{@options[:events].join(', ')}"
      puts "   Press #{EventPrinter::BOLD}Ctrl+C#{EventPrinter::RESET} anytime to stop and auto-delete the webhook."
      puts ("=" * 60) + "\n"

      # Keep main thread alive
      sleep
    rescue LocalCI::Error => e
      warn "\n#{EventPrinter::RED}❌ Error: #{e.message}#{EventPrinter::RESET}\n"
      exit 1
    rescue StandardError => e
      warn "\n#{EventPrinter::RED}💥 Unexpected error: #{e.message}#{EventPrinter::RESET}"
      warn e.backtrace.first(5).join("\n")
      exit 1
    end

    private

    def parse_options!
      parser = OptionParser.new do |opts|
        opts.banner = "Usage: local-ci [options]"

        opts.on("-p", "--port PORT", Integer, "Port for local HTTP server (default: 4567)") do |p|
          @options[:port] = p
        end

        opts.on("-r", "--remote REMOTE", String, "Git remote name to use (default: origin)") do |r|
          @options[:remote] = r
        end

        opts.on("-e", "--events EVENTS", Array, "Comma-separated GitHub events to listen for (default: push,pull_request,workflow_run,workflow_job)") do |e|
          @options[:events] = e
        end

        opts.on("-s", "--secret SECRET", String, "Custom HMAC-SHA256 webhook secret (auto-generated by default)") do |s|
          @options[:secret] = s
        end

        opts.on("--insecure", "Disable webhook signature verification") do
          @options[:insecure] = true
        end

        opts.on("--no-act", "Listen and print events only without running act") do
          @options[:act] = false
        end

        opts.on("--act-args ARGS", String, "Custom arguments to pass to act (e.g. '-j test')") do |args|
          @options[:act_args] = args.split
        end

        opts.on("--no-status", "Disable reporting commit statuses back to GitHub") do
          @options[:report_status] = false
        end

        opts.on("-v", "--version", "Show version") do
          puts "local-ci #{VERSION}"
          exit 0
        end

        opts.on("-h", "--help", "Show help message") do
          puts opts
          exit 0
        end
      end

      parser.parse!(@argv)
    end

    def print_banner
      puts "\n"
      puts "#{EventPrinter::CYAN}======================================================#{EventPrinter::RESET}"
      puts "#{EventPrinter::BOLD} 🚀 Local CI Runner - Live GitHub Webhook Listener#{EventPrinter::RESET}"
      puts "#{EventPrinter::CYAN}======================================================#{EventPrinter::RESET}\n"
    end
  end
end
